### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by mercymugambi** [yusufobr/awesome-books#3]
## Issues to be fixed

- Good job so far however there is an issue that you need to.  On your book list alternate the bg- colors from grey to white. 
- hint: you can apply this on css by assigning the nth child (odd) and background color. 

```
.collection ul:nth-child(odd) {
  background-color: rgb(243, 239, 239);
}
```

**Comment by yusufobr** [comment]
Hi @mercymugambi , thank you for your comments, the required changes are being considered.
